name: CI

on:	
  push:	
    branches: [ main ]	
  pull_request:	
    branches: [ main ]

jobs:
  building Game:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sfml
      run: |
         sudo apt update
         sudo apt-get install libsfml-dev
    - name: List files
      run: ls
    - name: Build
      run: make
    